force-app/main/default/objects/Lead/fields/ProductInterest__c.field-meta.xml
<CustomField>
    <fullName>ProductInterest__c</fullName>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GC1000 series</fullName>
                <isActive>true</isActive>
                <label>GC1000 series</label>
            </value>
            <value>
                <fullName>GC5000 series</fullName>
                <isActive>true</isActive>
                <label>GC5000 series</label>
            </value>
            <value>
                <fullName>GC3000 series</fullName>
                <isActive>true</isActive>
                <label>GC3000 series</label>
            </value>
        </valueSetDefinition>
    </valueSet>
    <label>Product Interest</label>
</CustomField>

force-app/main/default/classes/TopLevelClass.cls
public with sharing class TopLevelClass {
    //20250124-072518
    @InvocableMethod(label='Delegate to apex')
    public static void doSomething(){

        RightClass right = new RightClass();
        LeftClass left = new LeftClass();
        //new comment

        //List<Lead> leads = [SELECT ProductInterest__c ,Connected_Org__c FROM Lead];
        //Audit team changes..

    }
    
    public static void doNothing(){
        String company = 'Salto';
    }
}